esphome:
  name: envirosentry
  name_add_mac_suffix: true

esp32:
  board: esp32-poe
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

logger:
  level: INFO
  baud_rate: 0  # disable UART logging if bridge_uart will be used later

api:

ota:

# Optional: announce presence for easier adoption
dashboard_import:
  package_import_url: github://SteveJonesPSD/envirosentry/envirosentry.yaml@main
  import_full_config: true

text_sensor:
  - platform: version
    name: "Firmware Version"